import BayesianNetworksProofs.Finite.BayesNet
import Mathlib.Algebra.Ring.Defs
import Mathlib.Algebra.BigOperators.Group.Finset.Piecewise

/-!
# InfluenceDiagramsProofs.Finite.InfluenceDiagram

**Concrete finite influence diagrams** — the semantic model behind `InfluenceDiagrams.jl`
(SPEC §23–§27, §36, §37).

A `FinInfluenceDiagram` extends the finite Bayesian-network shape `FinBayesNet` of the
BayesianNetworks proofs project (chance variables `V`, chance mechanisms `M`, `states`, `target`,
`parents`) with

* a finite type `D` of decisions, each controlling an `action` variable and reading an
  information set `info d` (the `Decision` / `InformationInput` rows of `SchInfluenceDiagram`);
* a finite type `U` of utility nodes, each reading a scope `uscope j`
  (the `Utility` / `UtilityInput` rows).

Kernels (chance), policies (decisions) and utilities live outside the structure, exactly as
`kernel_ref` / `utility_ref` point outside the ACSet in Julia.

Validity (SPEC §37):

* `GeneratorsDisjoint` — no variable is both a mechanism target and an action (item 2);
* `GeneratorsCover` — every variable is a mechanism target or an action;
* `Closed` — `Sum.elim target action : M ⊕ D → V` is bijective, i.e. every variable has exactly
  one generator, mechanism or decision (items 1, 2 together with `closed_iff`);
* `IDOrder` — a topological order of the variables in which parents precede mechanism targets and
  information variables precede actions (items 4, 8, 11).

A `Policy id R d` is a normalised kernel `Assignment → states (action d) → R` that reads only
`info d` (`LocalOn`) (SPEC §26). Over `ℝ`, nonnegativity must be supplied separately for a
stochastic interpretation (`Strategy.Nonneg` in `Optimization.lean`). A deterministic policy is `Policy.ofFun`, a
constant one `Policy.const`. A `Strategy id R` is one policy per decision — complete by
construction (SPEC §27).
-/

set_option autoImplicit false

namespace InfluenceDiagramsProofs

open BayesianNetworksProofs BayesianNetworksProofs.FinBayesNet

/-- A finite influence-diagram *shape*: a finite Bayesian-network shape plus decisions
(action variable, information set) and utility nodes (scope). -/
structure FinInfluenceDiagram extends FinBayesNet where
  /-- Decisions (one per `Decision` row of the ACSet). -/
  D : Type
  [fintypeD : Fintype D]
  [decD : DecidableEq D]
  /-- The action variable controlled by each decision (`decision_variable`). -/
  action : D → V
  /-- The information set `I_D` of each decision (the `InformationInput` rows). -/
  info : D → Finset V
  /-- Utility nodes (one per `Utility` row). -/
  U : Type
  [fintypeU : Fintype U]
  [decU : DecidableEq U]
  /-- The variables read by each utility node (the `UtilityInput` rows). -/
  uscope : U → Finset V

attribute [instance] FinInfluenceDiagram.fintypeD FinInfluenceDiagram.decD
  FinInfluenceDiagram.fintypeU FinInfluenceDiagram.decU

namespace FinInfluenceDiagram

variable (id : FinInfluenceDiagram)

/-! ## Generators and validity -/

/-- Every variable is generated by a mechanism or by a decision. -/
def generator : id.M ⊕ id.D → id.V := Sum.elim id.target id.action

@[simp] theorem generator_inl (m : id.M) : id.generator (.inl m) = id.target m := rfl

@[simp] theorem generator_inr (d : id.D) : id.generator (.inr d) = id.action d := rfl

/-- No variable is both a mechanism target and a decision action (SPEC §37 item 2: an
uninstantiated action has no chance mechanism). -/
def GeneratorsDisjoint : Prop := ∀ m d, id.target m ≠ id.action d

/-- Every variable is a mechanism target or a decision action. -/
def GeneratorsCover : Prop := ∀ v, (∃ m, id.target m = v) ∨ (∃ d, id.action d = v)

/-- Closed influence diagram: every variable has exactly one generator — a chance mechanism or a
decision (`validate` items 1 and 2 plus closedness of the chance part). -/
def Closed : Prop := Function.Bijective id.generator

/-- `Closed` unpacked: both generator maps are injective, disjoint and jointly cover `V`. -/
theorem closed_iff :
    id.Closed ↔ Function.Injective id.target ∧ Function.Injective id.action ∧
      id.GeneratorsDisjoint ∧ id.GeneratorsCover := by
  constructor
  · rintro ⟨hinj, hsurj⟩
    refine ⟨fun m m' h => ?_, fun d d' h => ?_, fun m d h => ?_, fun v => ?_⟩
    · exact Sum.inl_injective (hinj (a₁ := .inl m) (a₂ := .inl m') h)
    · exact Sum.inr_injective (hinj (a₁ := .inr d) (a₂ := .inr d') h)
    · exact Sum.inl_ne_inr (hinj (a₁ := .inl m) (a₂ := .inr d) h)
    · obtain ⟨g, hg⟩ := hsurj v
      cases g with
      | inl m => exact Or.inl ⟨m, hg⟩
      | inr d => exact Or.inr ⟨d, hg⟩
  · rintro ⟨hT, hA, hdisj, hcover⟩
    refine ⟨fun g g' h => ?_, fun v => ?_⟩
    · cases g with
      | inl m =>
        cases g' with
        | inl m' => exact congrArg Sum.inl (hT h)
        | inr d' => exact absurd h (hdisj m d')
      | inr d =>
        cases g' with
        | inl m' => exact absurd h.symm (hdisj m' d)
        | inr d' => exact congrArg Sum.inr (hA h)
    · rcases hcover v with ⟨m, hm⟩ | ⟨d, hd⟩
      · exact ⟨.inl m, hm⟩
      · exact ⟨.inr d, hd⟩

/-- Build `Closed` from its four components. -/
theorem Closed.of (hT : Function.Injective id.target) (hA : Function.Injective id.action)
    (hdisj : id.GeneratorsDisjoint) (hcover : id.GeneratorsCover) : id.Closed :=
  id.closed_iff.2 ⟨hT, hA, hdisj, hcover⟩

/-- A topological order of the influence diagram: a duplicate-free complete list of the variables
in which every parent of a mechanism precedes its target and every information variable of a
decision precedes its action; no generator reads the variable it generates (SPEC §37 items 4,
8, 11; the decision precedence is the induced order of the actions). -/
structure IDOrder where
  order : List id.V
  nodup : order.Nodup
  complete : ∀ v, v ∈ order
  /-- For `a` before `b`, `b` is not a parent of the mechanism generating `a`. -/
  parents_before : order.Pairwise (fun a b => ∀ m, id.target m = a → b ∉ id.parents m)
  /-- For `a` before `b`, `b` is not an information variable of the decision controlling `a`
  (information is available before the decision is taken). -/
  info_before_action : order.Pairwise (fun a b => ∀ d, id.action d = a → b ∉ id.info d)
  no_self : ∀ m, id.target m ∉ id.parents m
  no_self_info : ∀ d, id.action d ∉ id.info d

/-! ## Policies and strategies -/

variable {id} {R : Type} [CommSemiring R]

/-- A policy for decision `d`: a normalised kernel from assignments to actions that reads only
the information set `info d` (SPEC §26, §37 item 9). Real-valued policies may be signed unless
nonnegativity is required separately. -/
structure Policy (id : FinInfluenceDiagram) (R : Type) [CommSemiring R] (d : id.D) where
  /-- `kernel x a` is the weight of action `a` given assignment `x`. -/
  kernel : id.Assignment → id.states (id.action d) → R
  /-- The policy reads only its information set. -/
  localOn : LocalOn (id.info d) kernel
  /-- Action weights sum to one; nonnegativity is a separate condition over `ℝ`. -/
  normalised : ∀ x, ∑ a, kernel x a = 1

/-- A complete strategy: one policy per decision (SPEC §27, §37 item 10). -/
abbrev Strategy (id : FinInfluenceDiagram) (R : Type) [CommSemiring R] :=
  (d : id.D) → Policy id R d

namespace Policy

variable {d : id.D}

/-- A deterministic policy `δ : I_D → A_D`, given as a function of the whole assignment that
depends only on the information set. -/
def ofFun (f : id.Assignment → id.states (id.action d))
    (hf : ∀ x x' : id.Assignment, (∀ p ∈ id.info d, x p = x' p) → f x = f x') : Policy id R d where
  kernel x a := if a = f x then 1 else 0
  localOn x x' h := by
    funext a
    dsimp only
    rw [hf x x' h]
  normalised x := by simp

@[simp] theorem ofFun_kernel (f : id.Assignment → id.states (id.action d)) (hf)
    (x : id.Assignment) (a : id.states (id.action d)) :
    (ofFun (R := R) f hf).kernel x a = if a = f x then 1 else 0 := rfl

/-- The constant policy always choosing the action `a` (`fix_decision`, SPEC §41). -/
def const (d : id.D) (a : id.states (id.action d)) : Policy id R d where
  kernel _ b := if b = a then 1 else 0
  localOn _ _ _ := rfl
  normalised _ := by simp

@[simp] theorem const_kernel (d : id.D) (a : id.states (id.action d)) (x : id.Assignment)
    (b : id.states (id.action d)) : (const (R := R) d a).kernel x b = if b = a then 1 else 0 := rfl

/-- The constant policy reads no variable at all: it is local for *every* information set. -/
theorem const_localOn (d : id.D) (a : id.states (id.action d)) (P : Finset id.V) :
    LocalOn P (const (R := R) d a).kernel := fun _ _ _ => rfl

/-- In particular it is local for the empty information set. -/
theorem const_localOn_empty (d : id.D) (a : id.states (id.action d)) :
    LocalOn ∅ (const (R := R) d a).kernel :=
  const_localOn d a ∅

end Policy

namespace Strategy

/-- `fix_decision`: replace the policy of `d` by the constant policy at `a` (SPEC §41). -/
def fix (σ : Strategy id R) (d : id.D) (a : id.states (id.action d)) : Strategy id R :=
  Function.update σ d (Policy.const d a)

@[simp] theorem fix_self (σ : Strategy id R) (d : id.D) (a : id.states (id.action d)) :
    σ.fix d a d = Policy.const d a := by
  simp [fix]

theorem fix_of_ne (σ : Strategy id R) {d d' : id.D} (h : d' ≠ d) (a : id.states (id.action d)) :
    σ.fix d a d' = σ d' := by
  simp [fix, Function.update_of_ne h]

end Strategy

end FinInfluenceDiagram

end InfluenceDiagramsProofs
